name: Publish Manual to JFrog
on:
  workflow_dispatch:
    inputs:
      buildRef:
        description: Ref to build (commit, branch, or refs/pull/1234/head or refs/pull/1234/merge)
        required: true
        default: refs/pull/1234/merge
      version:
        description: 'The version to publish to jfrog'
        required: false

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
      id: extract_branch
    - name: Update the version
      run: |
        sh .github/scripts/version-upgrade.sh ${{ steps.extract_branch.outputs.branch }} ${{ inputs.version }}
    - name: Build with Maven
      run: |
        mvn clean deploy -DskipTests -s .github/workflows/settings.xml -DretryFailedDeploymentCount=3
      env:
        MVN_DEPLOY_JFROG_KEY: ${{ secrets.MVN_DEPLOY_JFROG_KEY }}
        MVN_DEPLOY_JFROG_USER: ${{ secrets.MVN_DEPLOY_JFROG_USER }}
